sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- 6.9.0
before_install:
- npm i -g npm@3
before_script:
- npm prune
after_success:
- npm run coverage:upload
- npm run semantic-release
