sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- 6.9.0
before_install:
- npm i -g npm@3
before_script:
- npm prune
after_success:
- npm run coverage:upload
- npm run semantic-release
env:
  global:
  - secure: iYWheUrQe8wf5hzHv1yIMrPZdzmbQ5v+CEc1MyB8rsbYNoHz8tMWIfYv+rhWE6ByFNI9Oxi/nRRIhCUdDRk3wGQ89Y6XLOdLFibM7BkeeMIzlZmYdh30IABM5FB05TnVEL4zcjt7JlIbBhmBfFddF0Vu183+XuWAcuetQUVW8QCJ04mnLmtCOn5SuJwn11fn44cHZukc/HC5zebmD3Lbr8ybZTt7ouas0Z6ro/7YzKG14An6MENC49jbO/zgPRUTVSJ01oCKWOVa3Buh/9tbxQpvD6BmonwKP8aq01bD6gBCelo6zgi0w0xlJYJWhr2B63BCcDdfRRlUzQ3hPT7XEJu+lkHMw0q4O5Znn3vigdjV7rpkYzX/56sS14XIKgT80nMuYxiw8TEt0RovfMXyR10rmGaf3GvAmNtWz1w3EaHs0hNAZ+mhrhdDgK/RFwocqr9gLm+CgEjAqA9TKW2K2MntGZgQU6IFCRqnvIJzJdWkr+zG6tlYw4lck9bqtsRj15RIRvgmEwLkppPKQVfshnWsphrJi+ouGbXcr7LkSQ+kq2ylo8Mkz9iosZVOpMOkrj/vKg3ZOKPrQK/45lKq5bh6N2DQe9lnCuLKf5DnhDYusWLMQ1UmtyQVNJK9ePiouBqxazSJeH35mSzGpGRQV5Sbf6mgOCszMK7A9fiS9js=
  - secure: Dyskl3djVF4PbnokKnpum3EvR0S0ZhyEGnwAmCR2auOL9sSRtzAgyh3i+Ir88JjOX4OVb1vQ4u5D2RW2O/LNnkZdfhA0KsxwS+b9ody/00jwj3m2LeBU1znoJi/ImQYZ7PrjzhmLMeJzK3g7x/45eZUeDqkK8qiUPxUJeqRrUP5jbbPbJuZrGusTYQR88y8q2RitUjCZKloEke/Jh7esOqB57/PRar5Jorsub2AylRvYQVzgq75LhGltcRAASiiSEcBiCSkOrblIJl3y3PjK3cP2RanjDjED4pWX5OHyC/469FeMGzXuUUPxuN+ITWXSgLHAIjfWiO6h/Z7UTEUos6Ydze1u0EmUwhlRaCSHNS/RlfYKhouhP9LZ5ZLrzaPnmocQSrdNDL6JMXtmYvFm1ZXb3rXN7JTFwJuTopzbFeAB7bI318BRTBf0dbAlOg7jX/2uMF5Zc2GRV+ERyYfCENounUcwaJ6XqBNY5fYFcLKVG9B1qXO/9zIi055CWKrJ1uvuyHtsqUi/tIFZLBZURa09Kv014qcXH1YPdp0Kbze2SV/o05tqszDJCRklQUVlbhrIEgnxexWBhH+u62/S6xzwhWg4GPItQJBN6qKj36zeMB/MzbKe7t/SVqqQPWiJ3Sao10soXm8iezcsNW247r68Qewv42EM1sHSgK5DQAU=
